# Generated by Django 4.0.4 on 2022-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=50)),
                ('agencia_origem', models.CharField(max_length=50)),
                ('conta_origem', models.CharField(max_length=50)),
                ('banco_destino', models.CharField(max_length=50)),
                ('agencia_destino', models.CharField(max_length=50)),
                ('conta_destino', models.CharField(max_length=50)),
                ('valor_transacao', models.CharField(max_length=50)),
                ('data_hora_transacao', models.CharField(max_length=50)),
            ],
        ),
    ]
