# Generated by Django 4.0.4 on 2022-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='agencia_destino',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='controller',
            name='agencia_origem',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='controller',
            name='banco_destino',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='controller',
            name='banco_origem',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='controller',
            name='conta_destino',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='controller',
            name='conta_origem',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='controller',
            name='data_hora_transacao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='controller',
            name='valor_transacao',
            field=models.CharField(max_length=150),
        ),
    ]
