# Generated by Django 4.0.4 on 2022-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_alter_controller_agencia_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transacoes', models.CharField(max_length=150)),
            ],
        ),
    ]
