# Generated by Django 4.0.4 on 2022-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0003_dataimportacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataimportacoes',
            old_name='data_transacoes',
            new_name='data_importacao',
        ),
        migrations.AddField(
            model_name='dataimportacoes',
            name='data_transacao',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
