# Generated by Django 4.0.4 on 2022-04-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0004_rename_data_transacoes_dataimportacoes_data_importacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportacoes',
            name='id_usuario',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
